name: Reusable Promote Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      registry:
        required: true
        type: string
      registry_user:
        required: true
        type: string
      promote_to:
        required: true
        type: choice
        options:
          - beta
          - production
    secrets:
      GH_TOKEN:
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Determine source tag (auto-pick from GitVersion)
        id: resolve
        run: |
              # Automatically using the provided tag (from GitVersion output in the service workflow)
              echo "Using provided tag: ${{ inputs.promote_to }}"
              FROM_TAG="${{ inputs.promote_to }}"
              echo "from_tag=$FROM_TAG" >> $GITHUB_OUTPUT

      - name: Promote to new tag
        run: |
              # Automatically determine the correct version based on the 'FROM_TAG' variable
              TO_TAG=""
              
              if [[ "$FROM_TAG" == *"alpha"* ]]; then
                TO_TAG=$(echo $FROM_TAG | sed 's/alpha/beta/')
              elif [[ "$FROM_TAG" == *"beta"* ]]; then
                TO_TAG=$(echo $FROM_TAG | sed 's/-alpha\..*//; s/-beta\..*//')
              else
                echo "❌ Invalid tag format"; exit 1
              fi
              
              echo "Promoting $FROM_TAG → $TO_TAG"
              
              docker pull ${{ inputs.registry }}/${{ inputs.image_name }}:$FROM_TAG
              
              echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ inputs.registry_user }} --password-stdin
              
              docker tag ${{ inputs.registry }}/${{ inputs.image_name }}:$FROM_TAG \
                         ${{ inputs.registry }}/${{ inputs.image_name }}:$TO_TAG
              
              docker push ${{ inputs.registry }}/${{ inputs.image_name }}:$TO_TAG
